# Catalog Server configuration
server.host=0.0.0.0
server.port=4600

# Logging
log.level=INFO
log.dir=/var/log/argus-catalog-server
log.filename=argus-catalog-server.log

# CORS
cors.origins=*

# Added for SSO AUTH - Keycloak OIDC settings
auth.type=local
auth.keycloak.server_url=http://localhost:8180
auth.keycloak.realm=argus
auth.keycloak.client_id=argus-client
auth.keycloak.client_secret=argus-client-secret
auth.keycloak.admin_role=argus-admin
auth.keycloak.superuser_role=argus-superuser
auth.keycloak.user_role=argus-user

# Database
db.type=postgresql
db.host=localhost
db.port=5432
db.name=argus_catalog
db.username=argus
db.password=argus
