# Catalog Server configuration
server.host=0.0.0.0
server.port=4600

# Logging
log.level=INFO
log.dir=/var/log/argus-catalog-server
log.filename=argus-catalog-server.log

# CORS
cors.origins=*

# Added for SSO AUTH - Keycloak OIDC settings
auth.type=keycloak
auth.keycloak.server_url=http://localhost:8180
auth.keycloak.realm=argus-catalog
auth.keycloak.client_id=argus-catalog-server
auth.keycloak.client_secret=argus-catalog-server-secret
auth.keycloak.admin_role=catalog-admin
auth.keycloak.user_role=catalog-user

# Database
db.type=postgresql
db.host=localhost
db.port=5432
db.name=argus_catalog
db.username=argus
db.password=argus
