apiVersion: v1
kind: Secret
metadata:
  name: argus-vllm-${WORKSPACE_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: vllm
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
type: Opaque
stringData:
  hf-token: "${HF_TOKEN}"
