"""
Platform metadata seed data for the catalog server.

Each platform key matches catalog_platforms.name. Values contain:
- data_types: list of (type_name, type_category, description)
- table_types: list of (type_name, display_name, description, is_default)
- storage_formats: list of (format_name, display_name, description, is_default)
- features: list of (feature_key, display_name, description, value_type, is_required)
"""

PLATFORM_METADATA = {
    "hive": {
        "data_types": [
            ("BOOLEAN", "boolean", "True/false values"),
            ("TINYINT", "numeric", "1-byte signed integer (-128 to 127)"),
            ("SMALLINT", "numeric", "2-byte signed integer (-32,768 to 32,767)"),
            ("INT", "numeric", "4-byte signed integer"),
            ("BIGINT", "numeric", "8-byte signed integer"),
            ("FLOAT", "numeric", "4-byte single precision floating point"),
            ("DOUBLE", "numeric", "8-byte double precision floating point"),
            ("DECIMAL", "numeric", "Arbitrary precision decimal"),
            ("STRING", "string", "Variable-length character string"),
            ("VARCHAR", "string", "Variable-length character string with max length"),
            ("CHAR", "string", "Fixed-length character string"),
            ("DATE", "datetime", "Calendar date (YYYY-MM-DD)"),
            ("TIMESTAMP", "datetime", "Date and time with nanosecond precision"),
            ("BINARY", "binary", "Variable-length binary data"),
            ("ARRAY", "complex", "Ordered collection of elements"),
            ("MAP", "complex", "Key-value pairs"),
            ("STRUCT", "complex", "Named fields with typed values"),
            ("UNIONTYPE", "complex", "Union of multiple types"),
        ],
        "table_types": [
            ("MANAGED_TABLE", "Managed Table", "Hive manages both data and metadata lifecycle", "true"),
            ("EXTERNAL_TABLE", "External Table", "Hive manages metadata only; data lifecycle managed externally", "false"),
            ("VIRTUAL_VIEW", "View", "Virtual view defined by a query", "false"),
            ("MATERIALIZED_VIEW", "Materialized View", "Pre-computed view stored physically", "false"),
        ],
        "storage_formats": [
            ("ORC", "ORC", "Optimized Row Columnar format, best for Hive", "true"),
            ("PARQUET", "Parquet", "Apache Parquet columnar format", "false"),
            ("AVRO", "Avro", "Apache Avro row-based format with schema", "false"),
            ("TEXTFILE", "TextFile", "Plain text with delimiters", "false"),
            ("SEQUENCEFILE", "SequenceFile", "Hadoop binary key-value format", "false"),
            ("RCFILE", "RCFile", "Record Columnar File format", "false"),
            ("JSONFILE", "JSON", "JSON format, one object per line", "false"),
        ],
        "features": [
            ("location", "Location", "HDFS location path for the table data (required for external tables)", "text", "false"),
            ("serde", "SerDe", "Serializer/Deserializer class (e.g. org.apache.hadoop.hive.serde2.lazy.LazySimpleSerDe)", "text", "false"),
            ("input_format", "Input Format", "Hadoop InputFormat class", "text", "false"),
            ("output_format", "Output Format", "Hadoop OutputFormat class", "text", "false"),
            ("compression", "Compression", "Compression codec (SNAPPY, GZIP, LZ4, ZSTD, NONE)", "text", "false"),
            ("field_delimiter", "Field Delimiter", "Column delimiter for TEXTFILE (e.g. \\t, |, ,)", "text", "false"),
            ("line_delimiter", "Line Delimiter", "Row delimiter (default: \\n)", "text", "false"),
            ("collection_delimiter", "Collection Delimiter", "Delimiter for ARRAY/MAP elements", "text", "false"),
            ("map_key_delimiter", "Map Key Delimiter", "Delimiter between MAP key and value", "text", "false"),
            ("partition_keys", "Partition Keys", "Columns used for table partitioning (e.g. dt, region)", "column_list", "false"),
            ("bucket_columns", "Bucket Columns", "Columns used for bucketing/clustering", "column_list", "false"),
            ("bucket_count", "Bucket Count", "Number of buckets for clustered tables", "number", "false"),
            ("sort_columns", "Sort Columns", "Columns used for sorting within buckets", "column_list", "false"),
            ("transactional", "Transactional", "ACID transactional table (managed tables only)", "boolean", "false"),
            ("table_format", "Table Format", "Table format identifier (e.g. iceberg for Iceberg tables)", "text", "false"),
            ("tbl_properties", "Table Properties", "Additional TBLPROPERTIES key-value pairs (JSON)", "text", "false"),
            ("estimated_rows", "Estimated Rows", "Approximate number of rows (from ANALYZE TABLE)", "number", "false"),
            ("total_size", "Total Size", "Total data size in bytes", "number", "false"),
            ("num_files", "Number of Files", "Number of data files in HDFS", "number", "false"),
        ],
    },
    "mysql": {
        "data_types": [
            ("TINYINT", "numeric", "1-byte integer"),
            ("SMALLINT", "numeric", "2-byte integer"),
            ("MEDIUMINT", "numeric", "3-byte integer"),
            ("INT", "numeric", "4-byte integer"),
            ("BIGINT", "numeric", "8-byte integer"),
            ("FLOAT", "numeric", "Single precision floating point"),
            ("DOUBLE", "numeric", "Double precision floating point"),
            ("DECIMAL", "numeric", "Exact fixed-point number"),
            ("CHAR", "string", "Fixed-length string"),
            ("VARCHAR", "string", "Variable-length string"),
            ("TINYTEXT", "string", "Up to 255 bytes text"),
            ("TEXT", "string", "Up to 65,535 bytes text"),
            ("MEDIUMTEXT", "string", "Up to 16MB text"),
            ("LONGTEXT", "string", "Up to 4GB text"),
            ("BINARY", "binary", "Fixed-length binary"),
            ("VARBINARY", "binary", "Variable-length binary"),
            ("BLOB", "binary", "Binary large object"),
            ("BOOLEAN", "boolean", "True/false (alias for TINYINT(1))"),
            ("DATE", "datetime", "Date (YYYY-MM-DD)"),
            ("TIME", "datetime", "Time (HH:MM:SS)"),
            ("DATETIME", "datetime", "Date and time"),
            ("TIMESTAMP", "datetime", "Timestamp with auto-update"),
            ("YEAR", "datetime", "Year value"),
            ("ENUM", "other", "Enumeration of string values"),
            ("SET", "other", "Set of string values"),
            ("JSON", "complex", "JSON document"),
            ("GEOMETRY", "spatial", "Spatial geometry type"),
            ("POINT", "spatial", "Spatial point type"),
        ],
        "table_types": [
            ("TABLE", "Table", "Standard InnoDB table", "true"),
            ("VIEW", "View", "Virtual table defined by a query", "false"),
            ("TEMPORARY_TABLE", "Temporary Table", "Session-scoped temporary table", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("engine", "Storage Engine", "MySQL storage engine (InnoDB, MyISAM, MEMORY)", "text", "false"),
            ("partition_keys", "Partition Keys", "Columns used for partitioning", "column_list", "false"),
            ("partition_type", "Partition Type", "Partitioning method (RANGE, LIST, HASH, KEY)", "text", "false"),
            ("charset", "Character Set", "Default character set (utf8mb4)", "text", "false"),
        ],
    },
    "postgresql": {
        "data_types": [
            ("smallint", "numeric", "2-byte signed integer"),
            ("integer", "numeric", "4-byte signed integer"),
            ("bigint", "numeric", "8-byte signed integer"),
            ("numeric", "numeric", "Arbitrary precision number"),
            ("real", "numeric", "4-byte floating point"),
            ("double precision", "numeric", "8-byte floating point"),
            ("serial", "numeric", "Auto-incrementing 4-byte integer"),
            ("bigserial", "numeric", "Auto-incrementing 8-byte integer"),
            ("varchar", "string", "Variable-length string"),
            ("char", "string", "Fixed-length string"),
            ("text", "string", "Unlimited length string"),
            ("boolean", "boolean", "True/false"),
            ("date", "datetime", "Calendar date"),
            ("time", "datetime", "Time of day"),
            ("timestamp", "datetime", "Date and time without timezone"),
            ("timestamptz", "datetime", "Date and time with timezone"),
            ("interval", "datetime", "Time interval"),
            ("uuid", "other", "Universally unique identifier"),
            ("json", "complex", "JSON text data"),
            ("jsonb", "complex", "JSON binary data (indexed)"),
            ("bytea", "binary", "Variable-length binary string"),
            ("inet", "other", "IPv4 or IPv6 address"),
            ("cidr", "other", "IPv4 or IPv6 network"),
            ("macaddr", "other", "MAC address"),
            ("xml", "other", "XML data"),
            ("money", "numeric", "Currency amount"),
            ("tsvector", "other", "Text search document"),
            ("tsquery", "other", "Text search query"),
            ("int4range", "other", "Range of integer"),
            ("tstzrange", "other", "Range of timestamptz"),
            ("array", "complex", "Array of any type"),
        ],
        "table_types": [
            ("TABLE", "Table", "Standard heap table", "true"),
            ("VIEW", "View", "Virtual table defined by a query", "false"),
            ("MATERIALIZED_VIEW", "Materialized View", "Cached result of a query", "false"),
            ("FOREIGN_TABLE", "Foreign Table", "Table accessed through a foreign data wrapper", "false"),
            ("PARTITIONED_TABLE", "Partitioned Table", "Table with declarative partitioning", "false"),
            ("TEMPORARY_TABLE", "Temporary Table", "Session-scoped temporary table", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("partition_keys", "Partition Keys", "Columns used for declarative partitioning", "column_list", "false"),
            ("partition_type", "Partition Type", "Partitioning method (RANGE, LIST, HASH)", "text", "false"),
            ("tablespace", "Tablespace", "Storage tablespace for the table", "text", "false"),
            ("fillfactor", "Fill Factor", "Page fill percentage for updates (10-100)", "number", "false"),
        ],
    },
    "kafka": {
        "data_types": [
            ("STRING", "string", "UTF-8 encoded string"),
            ("BYTES", "binary", "Raw byte array"),
            ("INT32", "numeric", "32-bit integer"),
            ("INT64", "numeric", "64-bit integer"),
            ("FLOAT32", "numeric", "32-bit float"),
            ("FLOAT64", "numeric", "64-bit float"),
            ("BOOLEAN", "boolean", "True/false"),
            ("AVRO", "complex", "Avro-encoded structured data"),
            ("JSON", "complex", "JSON-encoded data"),
            ("PROTOBUF", "complex", "Protocol Buffers encoded data"),
        ],
        "table_types": [
            ("TOPIC", "Topic", "Kafka topic for event streaming", "true"),
            ("STREAM", "Stream", "Continuous stream of events (Kafka Streams / ksqlDB)", "false"),
        ],
        "storage_formats": [
            ("AVRO", "Avro", "Apache Avro with Schema Registry", "true"),
            ("JSON", "JSON", "JSON serialization", "false"),
            ("PROTOBUF", "Protobuf", "Protocol Buffers serialization", "false"),
            ("STRING", "String", "Plain string serialization", "false"),
            ("BYTES", "Bytes", "Raw bytes", "false"),
        ],
        "features": [
            ("partition_count", "Partition Count", "Number of topic partitions", "number", "false"),
            ("replication_factor", "Replication Factor", "Number of replicas per partition", "number", "false"),
            ("retention_ms", "Retention (ms)", "Message retention period in milliseconds", "number", "false"),
            ("key_schema", "Key Schema", "Schema for message keys", "text", "false"),
            ("value_schema", "Value Schema", "Schema for message values", "text", "false"),
            ("cleanup_policy", "Cleanup Policy", "Log cleanup policy (delete, compact, delete+compact)", "text", "false"),
        ],
    },
    "s3": {
        "data_types": [],
        "table_types": [
            ("OBJECT", "Object", "S3 object (file)", "true"),
            ("PREFIX", "Prefix", "S3 prefix (directory-like path)", "false"),
        ],
        "storage_formats": [
            ("PARQUET", "Parquet", "Apache Parquet columnar format", "true"),
            ("ORC", "ORC", "Optimized Row Columnar format", "false"),
            ("AVRO", "Avro", "Apache Avro format", "false"),
            ("CSV", "CSV", "Comma-separated values", "false"),
            ("JSON", "JSON", "JSON lines format", "false"),
            ("TEXT", "Text", "Plain text format", "false"),
        ],
        "features": [
            ("bucket_name", "S3 Bucket", "Name of the S3 bucket", "text", "false"),
            ("prefix", "Key Prefix", "S3 key prefix path", "text", "false"),
            ("compression", "Compression", "Compression codec (GZIP, SNAPPY, LZ4, ZSTD, NONE)", "text", "false"),
            ("partition_keys", "Partition Keys", "Hive-style partition columns in path", "column_list", "false"),
        ],
    },
    "elasticsearch": {
        "data_types": [
            ("text", "string", "Full-text analyzed string"),
            ("keyword", "string", "Exact-match string (not analyzed)"),
            ("long", "numeric", "64-bit integer"),
            ("integer", "numeric", "32-bit integer"),
            ("short", "numeric", "16-bit integer"),
            ("byte", "numeric", "8-bit integer"),
            ("double", "numeric", "64-bit IEEE float"),
            ("float", "numeric", "32-bit IEEE float"),
            ("half_float", "numeric", "16-bit IEEE float"),
            ("boolean", "boolean", "True/false"),
            ("date", "datetime", "Date with optional time"),
            ("binary", "binary", "Base64 encoded binary"),
            ("object", "complex", "JSON object"),
            ("nested", "complex", "Array of objects (independent indexing)"),
            ("geo_point", "spatial", "Latitude/longitude point"),
            ("geo_shape", "spatial", "Arbitrary geo shape"),
            ("ip", "other", "IPv4 or IPv6 address"),
        ],
        "table_types": [
            ("INDEX", "Index", "Elasticsearch index", "true"),
            ("DATA_STREAM", "Data Stream", "Append-only time series data stream", "false"),
            ("ALIAS", "Alias", "Index alias for abstraction", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("shards", "Number of Shards", "Primary shard count", "number", "false"),
            ("replicas", "Number of Replicas", "Replica count per shard", "number", "false"),
            ("refresh_interval", "Refresh Interval", "Index refresh interval (e.g. 1s, 30s)", "text", "false"),
        ],
    },
    "mongodb": {
        "data_types": [
            ("String", "string", "UTF-8 string"),
            ("Int32", "numeric", "32-bit integer"),
            ("Int64", "numeric", "64-bit integer"),
            ("Double", "numeric", "64-bit IEEE float"),
            ("Decimal128", "numeric", "128-bit decimal"),
            ("Boolean", "boolean", "True/false"),
            ("Date", "datetime", "UTC datetime"),
            ("Timestamp", "datetime", "Internal MongoDB timestamp"),
            ("ObjectId", "other", "12-byte unique identifier"),
            ("BinData", "binary", "Binary data"),
            ("Array", "complex", "Ordered array"),
            ("Object", "complex", "Embedded document"),
            ("Null", "other", "Null value"),
            ("Regex", "other", "Regular expression"),
        ],
        "table_types": [
            ("COLLECTION", "Collection", "Standard document collection", "true"),
            ("VIEW", "View", "Read-only view defined by aggregation pipeline", "false"),
            ("TIMESERIES", "Time Series", "Time series collection optimized for time-based data", "false"),
            ("CAPPED", "Capped Collection", "Fixed-size collection with automatic FIFO eviction", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("shard_key", "Shard Key", "Field(s) used for sharding", "column_list", "false"),
            ("capped_size", "Capped Size (bytes)", "Maximum collection size for capped collections", "number", "false"),
        ],
    },
    "hdfs": {
        "data_types": [],
        "table_types": [
            ("FILE", "File", "HDFS file", "true"),
            ("DIRECTORY", "Directory", "HDFS directory", "false"),
        ],
        "storage_formats": [
            ("PARQUET", "Parquet", "Apache Parquet columnar format", "true"),
            ("ORC", "ORC", "Optimized Row Columnar format", "false"),
            ("AVRO", "Avro", "Apache Avro format", "false"),
            ("SEQUENCEFILE", "SequenceFile", "Hadoop binary key-value format", "false"),
            ("TEXT", "Text", "Plain text format", "false"),
            ("CSV", "CSV", "Comma-separated values", "false"),
        ],
        "features": [
            ("replication_factor", "Replication Factor", "HDFS block replication count", "number", "false"),
            ("block_size", "Block Size", "HDFS block size in bytes (default 128MB)", "number", "false"),
            ("compression", "Compression", "Compression codec (GZIP, SNAPPY, LZ4, ZSTD)", "text", "false"),
        ],
    },
    "snowflake": {
        "data_types": [
            ("NUMBER", "numeric", "Numeric value with precision and scale"),
            ("FLOAT", "numeric", "Double precision floating point"),
            ("VARCHAR", "string", "Variable-length string up to 16MB"),
            ("CHAR", "string", "Fixed-length or synonym for VARCHAR"),
            ("STRING", "string", "Alias for VARCHAR"),
            ("TEXT", "string", "Alias for VARCHAR"),
            ("BINARY", "binary", "Variable-length binary data"),
            ("BOOLEAN", "boolean", "True/false"),
            ("DATE", "datetime", "Calendar date"),
            ("TIME", "datetime", "Time of day"),
            ("TIMESTAMP_NTZ", "datetime", "Timestamp without timezone"),
            ("TIMESTAMP_LTZ", "datetime", "Timestamp with local timezone"),
            ("TIMESTAMP_TZ", "datetime", "Timestamp with timezone"),
            ("VARIANT", "complex", "Semi-structured data (JSON, Avro, etc.)"),
            ("OBJECT", "complex", "Key-value pairs (typed VARIANT)"),
            ("ARRAY", "complex", "Ordered array (typed VARIANT)"),
            ("GEOGRAPHY", "spatial", "Geospatial geography type"),
            ("GEOMETRY", "spatial", "Geospatial geometry type"),
        ],
        "table_types": [
            ("TABLE", "Table", "Permanent Snowflake table", "true"),
            ("EXTERNAL_TABLE", "External Table", "Table over external stage data", "false"),
            ("VIEW", "View", "Virtual view", "false"),
            ("MATERIALIZED_VIEW", "Materialized View", "Pre-computed materialized view", "false"),
            ("TEMPORARY_TABLE", "Temporary Table", "Session-scoped temporary table", "false"),
            ("TRANSIENT_TABLE", "Transient Table", "Table without Fail-safe period", "false"),
            ("ICEBERG_TABLE", "Iceberg Table", "Apache Iceberg managed table", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("cluster_keys", "Cluster Keys", "Columns for micro-partition clustering", "column_list", "false"),
            ("warehouse", "Warehouse", "Default virtual warehouse for queries", "text", "false"),
            ("retention_days", "Time Travel Retention", "Data retention period in days (0-90)", "number", "false"),
        ],
    },
    "bigquery": {
        "data_types": [
            ("INT64", "numeric", "64-bit integer"),
            ("NUMERIC", "numeric", "Exact numeric with 38 digits precision"),
            ("BIGNUMERIC", "numeric", "Exact numeric with 76 digits precision"),
            ("FLOAT64", "numeric", "64-bit floating point"),
            ("STRING", "string", "Variable-length Unicode string"),
            ("BYTES", "binary", "Variable-length binary data"),
            ("BOOL", "boolean", "True/false"),
            ("DATE", "datetime", "Calendar date"),
            ("TIME", "datetime", "Time of day"),
            ("DATETIME", "datetime", "Date and time without timezone"),
            ("TIMESTAMP", "datetime", "Absolute point in time with microseconds"),
            ("GEOGRAPHY", "spatial", "Geography (WGS84) type"),
            ("JSON", "complex", "Semi-structured JSON data"),
            ("ARRAY", "complex", "Ordered list of elements"),
            ("STRUCT", "complex", "Ordered collection of named fields"),
        ],
        "table_types": [
            ("TABLE", "Table", "Standard BigQuery table", "true"),
            ("EXTERNAL_TABLE", "External Table", "Table over external data (GCS, Bigtable, etc.)", "false"),
            ("VIEW", "View", "Logical view", "false"),
            ("MATERIALIZED_VIEW", "Materialized View", "Pre-computed materialized view", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("partition_keys", "Partition Column", "Column for time or range partitioning", "column_list", "false"),
            ("partition_type", "Partition Type", "Partitioning type (TIME, RANGE, INGESTION_TIME)", "text", "false"),
            ("cluster_keys", "Clustering Columns", "Columns for clustering (up to 4)", "column_list", "false"),
        ],
    },
    "redshift": {
        "data_types": [
            ("SMALLINT", "numeric", "2-byte integer"),
            ("INTEGER", "numeric", "4-byte integer"),
            ("BIGINT", "numeric", "8-byte integer"),
            ("DECIMAL", "numeric", "Exact numeric"),
            ("REAL", "numeric", "4-byte floating point"),
            ("DOUBLE PRECISION", "numeric", "8-byte floating point"),
            ("CHAR", "string", "Fixed-length string"),
            ("VARCHAR", "string", "Variable-length string up to 65535 bytes"),
            ("BOOLEAN", "boolean", "True/false"),
            ("DATE", "datetime", "Calendar date"),
            ("TIMESTAMP", "datetime", "Date and time without timezone"),
            ("TIMESTAMPTZ", "datetime", "Date and time with timezone"),
            ("SUPER", "complex", "Semi-structured data (JSON-like)"),
            ("GEOMETRY", "spatial", "Spatial geometry"),
            ("HLLSKETCH", "other", "HyperLogLog sketch"),
        ],
        "table_types": [
            ("TABLE", "Table", "Standard Redshift table", "true"),
            ("EXTERNAL_TABLE", "External Table", "Spectrum external table over S3", "false"),
            ("VIEW", "View", "Virtual view", "false"),
            ("MATERIALIZED_VIEW", "Materialized View", "Pre-computed view", "false"),
            ("LATE_BINDING_VIEW", "Late Binding View", "View without schema binding", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("dist_key", "Distribution Key", "Column for distribution across nodes", "column_list", "false"),
            ("dist_style", "Distribution Style", "Distribution style (KEY, EVEN, ALL, AUTO)", "text", "false"),
            ("sort_keys", "Sort Keys", "Columns for zone map ordering", "column_list", "false"),
            ("sort_style", "Sort Style", "Sort key type (COMPOUND, INTERLEAVED)", "text", "false"),
        ],
    },
    "trino": {
        "data_types": [
            ("BOOLEAN", "boolean", "True/false"),
            ("TINYINT", "numeric", "8-bit signed integer"),
            ("SMALLINT", "numeric", "16-bit signed integer"),
            ("INTEGER", "numeric", "32-bit signed integer"),
            ("BIGINT", "numeric", "64-bit signed integer"),
            ("REAL", "numeric", "32-bit IEEE 754 float"),
            ("DOUBLE", "numeric", "64-bit IEEE 754 float"),
            ("DECIMAL", "numeric", "Arbitrary precision decimal"),
            ("VARCHAR", "string", "Variable-length Unicode string"),
            ("CHAR", "string", "Fixed-length Unicode string"),
            ("VARBINARY", "binary", "Variable-length binary"),
            ("DATE", "datetime", "Calendar date"),
            ("TIME", "datetime", "Time of day with timezone"),
            ("TIMESTAMP", "datetime", "Date and time"),
            ("INTERVAL", "datetime", "Time interval (YEAR TO MONTH or DAY TO SECOND)"),
            ("ARRAY", "complex", "Ordered collection"),
            ("MAP", "complex", "Key-value pairs"),
            ("ROW", "complex", "Named fields (struct)"),
            ("JSON", "complex", "JSON value"),
            ("UUID", "other", "Universally unique identifier"),
            ("IPADDRESS", "other", "IPv4 or IPv6 address"),
            ("HyperLogLog", "other", "Approximate distinct count sketch"),
        ],
        "table_types": [
            ("TABLE", "Table", "Connector-managed table", "true"),
            ("VIEW", "View", "Virtual view", "false"),
            ("MATERIALIZED_VIEW", "Materialized View", "Pre-computed view (connector-dependent)", "false"),
        ],
        "storage_formats": [
            ("PARQUET", "Parquet", "Apache Parquet (Hive/Iceberg connector)", "true"),
            ("ORC", "ORC", "ORC format (Hive connector)", "false"),
            ("AVRO", "Avro", "Apache Avro (Hive connector)", "false"),
            ("CSV", "CSV", "CSV format", "false"),
            ("JSON", "JSON", "JSON format", "false"),
        ],
        "features": [
            ("connector", "Connector", "Trino connector type (hive, iceberg, delta, postgresql, mysql, etc.)", "text", "false"),
            ("partition_keys", "Partition Keys", "Columns used for partitioning", "column_list", "false"),
            ("bucket_count", "Bucket Count", "Number of buckets (Hive connector)", "number", "false"),
        ],
    },
    "starrocks": {
        "data_types": [
            ("BOOLEAN", "boolean", "True/false"),
            ("TINYINT", "numeric", "1-byte signed integer"),
            ("SMALLINT", "numeric", "2-byte signed integer"),
            ("INT", "numeric", "4-byte signed integer"),
            ("BIGINT", "numeric", "8-byte signed integer"),
            ("LARGEINT", "numeric", "16-byte signed integer"),
            ("FLOAT", "numeric", "4-byte floating point"),
            ("DOUBLE", "numeric", "8-byte floating point"),
            ("DECIMAL", "numeric", "Arbitrary precision decimal"),
            ("CHAR", "string", "Fixed-length string (1-255)"),
            ("VARCHAR", "string", "Variable-length string (1-1048576)"),
            ("STRING", "string", "Variable-length string (up to 65533 bytes)"),
            ("DATE", "datetime", "Date (YYYY-MM-DD)"),
            ("DATETIME", "datetime", "Date and time (YYYY-MM-DD HH:MM:SS)"),
            ("HLL", "other", "HyperLogLog for approximate distinct count"),
            ("BITMAP", "other", "Bitmap for exact distinct count"),
            ("PERCENTILE", "other", "Percentile approximation"),
            ("JSON", "complex", "Semi-structured JSON"),
            ("ARRAY", "complex", "Ordered array"),
            ("MAP", "complex", "Key-value pairs"),
            ("STRUCT", "complex", "Named fields"),
        ],
        "table_types": [
            ("DUPLICATE_KEY", "Duplicate Key Table", "Stores all rows; sorted by duplicate key columns", "true"),
            ("AGGREGATE_KEY", "Aggregate Key Table", "Pre-aggregates rows with same key", "false"),
            ("UNIQUE_KEY", "Unique Key Table", "Deduplicates by unique key (merge-on-read)", "false"),
            ("PRIMARY_KEY", "Primary Key Table", "Real-time update with delete+insert (fastest point lookup)", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("distribution_keys", "Distribution Keys", "Columns for hash distribution across BEs", "column_list", "true"),
            ("bucket_count", "Bucket Count", "Number of hash distribution buckets", "number", "false"),
            ("partition_keys", "Partition Keys", "Columns for range/list partitioning", "column_list", "false"),
            ("partition_type", "Partition Type", "Partitioning method (RANGE, LIST)", "text", "false"),
            ("sort_keys", "Sort Keys", "Columns for prefix index sorting", "column_list", "false"),
            ("replication_num", "Replication Number", "Number of tablet replicas (default 3)", "number", "false"),
        ],
    },
    "greenplum": {
        "data_types": [
            ("smallint", "numeric", "2-byte integer"),
            ("integer", "numeric", "4-byte integer"),
            ("bigint", "numeric", "8-byte integer"),
            ("numeric", "numeric", "Arbitrary precision number"),
            ("real", "numeric", "4-byte floating point"),
            ("double precision", "numeric", "8-byte floating point"),
            ("serial", "numeric", "Auto-incrementing 4-byte integer"),
            ("bigserial", "numeric", "Auto-incrementing 8-byte integer"),
            ("varchar", "string", "Variable-length string"),
            ("char", "string", "Fixed-length string"),
            ("text", "string", "Unlimited length string"),
            ("boolean", "boolean", "True/false"),
            ("date", "datetime", "Calendar date"),
            ("time", "datetime", "Time of day"),
            ("timestamp", "datetime", "Date and time"),
            ("timestamptz", "datetime", "Date and time with timezone"),
            ("interval", "datetime", "Time interval"),
            ("uuid", "other", "Universally unique identifier"),
            ("json", "complex", "JSON text data"),
            ("jsonb", "complex", "JSON binary data"),
            ("bytea", "binary", "Variable-length binary"),
            ("xml", "other", "XML data"),
            ("array", "complex", "Array of any type"),
        ],
        "table_types": [
            ("TABLE", "Table", "Standard Greenplum heap table", "true"),
            ("VIEW", "View", "Virtual view", "false"),
            ("MATERIALIZED_VIEW", "Materialized View", "Pre-computed view", "false"),
            ("EXTERNAL_TABLE", "External Table", "PXF/gpfdist external table", "false"),
            ("FOREIGN_TABLE", "Foreign Table", "Foreign data wrapper table", "false"),
        ],
        "storage_formats": [
            ("HEAP", "Heap", "Default row-oriented storage", "true"),
            ("AO_ROW", "Append-Optimized Row", "Append-optimized row storage with compression", "false"),
            ("AO_COLUMN", "Append-Optimized Column", "Append-optimized columnar storage", "false"),
        ],
        "features": [
            ("distributed_by", "Distributed By", "Columns for hash distribution across segments", "column_list", "false"),
            ("distributed_randomly", "Distributed Randomly", "Randomly distribute rows across segments", "boolean", "false"),
            ("partition_keys", "Partition Keys", "Columns for table partitioning", "column_list", "false"),
            ("partition_type", "Partition Type", "Partitioning method (RANGE, LIST)", "text", "false"),
            ("compression_type", "Compression", "Compression algorithm (ZLIB, ZSTD, QUICKLZ, RLE_TYPE, NONE)", "text", "false"),
            ("compresslevel", "Compression Level", "Compression level (1-9 for ZLIB, 1-19 for ZSTD)", "number", "false"),
        ],
    },
    "impala": {
        "data_types": [
            ("BOOLEAN", "boolean", "True/false"),
            ("TINYINT", "numeric", "1-byte integer"),
            ("SMALLINT", "numeric", "2-byte integer"),
            ("INT", "numeric", "4-byte integer"),
            ("BIGINT", "numeric", "8-byte integer"),
            ("FLOAT", "numeric", "4-byte floating point"),
            ("DOUBLE", "numeric", "8-byte floating point"),
            ("DECIMAL", "numeric", "Arbitrary precision decimal"),
            ("STRING", "string", "Variable-length string"),
            ("VARCHAR", "string", "Variable-length string with max length"),
            ("CHAR", "string", "Fixed-length string"),
            ("TIMESTAMP", "datetime", "Date and time with nanosecond precision"),
            ("DATE", "datetime", "Calendar date"),
            ("BINARY", "binary", "Variable-length binary"),
            ("ARRAY", "complex", "Ordered collection"),
            ("MAP", "complex", "Key-value pairs"),
            ("STRUCT", "complex", "Named fields"),
        ],
        "table_types": [
            ("MANAGED_TABLE", "Managed Table", "Impala/Hive managed table", "true"),
            ("EXTERNAL_TABLE", "External Table", "External table with separate data lifecycle", "false"),
            ("VIEW", "View", "Virtual view", "false"),
            ("KUDU_TABLE", "Kudu Table", "Table stored in Apache Kudu", "false"),
        ],
        "storage_formats": [
            ("PARQUET", "Parquet", "Apache Parquet (recommended for Impala)", "true"),
            ("ORC", "ORC", "Optimized Row Columnar", "false"),
            ("AVRO", "Avro", "Apache Avro", "false"),
            ("TEXTFILE", "TextFile", "Plain text with delimiters", "false"),
            ("SEQUENCEFILE", "SequenceFile", "Hadoop binary key-value", "false"),
            ("RCFILE", "RCFile", "Record Columnar File", "false"),
        ],
        "features": [
            ("location", "Location", "HDFS location path (required for external tables)", "text", "false"),
            ("serde", "SerDe", "Serializer/Deserializer class", "text", "false"),
            ("input_format", "Input Format", "Hadoop InputFormat class", "text", "false"),
            ("output_format", "Output Format", "Hadoop OutputFormat class", "text", "false"),
            ("compression", "Compression", "Compression codec (SNAPPY, GZIP, LZ4, ZSTD, NONE)", "text", "false"),
            ("field_delimiter", "Field Delimiter", "Column delimiter for TEXTFILE (e.g. \\t, |, ,)", "text", "false"),
            ("partition_keys", "Partition Keys", "Columns for table partitioning", "column_list", "false"),
            ("sort_columns", "Sort Columns", "Columns for sorted output", "column_list", "false"),
            ("kudu_master_hosts", "Kudu Master Hosts", "Kudu master addresses for Kudu tables", "text", "false"),
            ("table_format", "Table Format", "Table format identifier (e.g. iceberg)", "text", "false"),
            ("tbl_properties", "Table Properties", "Additional TBLPROPERTIES key-value pairs (JSON)", "text", "false"),
            ("estimated_rows", "Estimated Rows", "Approximate number of rows (from COMPUTE STATS)", "number", "false"),
            ("total_size", "Total Size", "Total data size in bytes", "number", "false"),
            ("num_files", "Number of Files", "Number of data files in HDFS", "number", "false"),
        ],
    },
    "kudu": {
        "data_types": [
            ("BOOL", "boolean", "True/false"),
            ("INT8", "numeric", "8-bit signed integer"),
            ("INT16", "numeric", "16-bit signed integer"),
            ("INT32", "numeric", "32-bit signed integer"),
            ("INT64", "numeric", "64-bit signed integer"),
            ("FLOAT", "numeric", "32-bit IEEE float"),
            ("DOUBLE", "numeric", "64-bit IEEE float"),
            ("DECIMAL", "numeric", "Exact decimal (precision 18/38)"),
            ("STRING", "string", "UTF-8 encoded string"),
            ("VARCHAR", "string", "Variable-length UTF-8 string with max length"),
            ("BINARY", "binary", "Arbitrary binary data"),
            ("DATE", "datetime", "Calendar date"),
            ("UNIXTIME_MICROS", "datetime", "Timestamp as microseconds since Unix epoch"),
        ],
        "table_types": [
            ("TABLE", "Table", "Kudu columnar table with primary key", "true"),
        ],
        "storage_formats": [],
        "features": [
            ("primary_keys", "Primary Keys", "Primary key columns (required, determines row uniqueness)", "column_list", "true"),
            ("hash_partitions", "Hash Partitions", "Number of hash partition buckets", "number", "false"),
            ("hash_columns", "Hash Columns", "Columns for hash partitioning", "column_list", "false"),
            ("range_partition_keys", "Range Partition Keys", "Columns for range partitioning", "column_list", "false"),
            ("replication_factor", "Replication Factor", "Tablet replication factor (default 3)", "number", "false"),
        ],
    },
    "java": {
        "data_types": [],
        "table_types": [
            ("TABLE", "Table", "Database table referenced in Java source code", "true"),
            ("VIEW", "View", "Database view referenced in Java source code", "false"),
            ("ENTITY", "JPA Entity", "JPA entity class mapped to a database table", "false"),
            ("JOIN_TABLE", "Join Table", "Association table for many-to-many relationships", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("source_file", "Source File", "Java source file path where the table is referenced", "text", "false"),
            ("package_name", "Package Name", "Java package of the class referencing the table", "text", "false"),
            ("class_or_method", "Class / Method", "Class or method name where the table reference was found", "text", "false"),
            ("java_version", "Java Version", "Java version detected from pom.xml or build.gradle", "text", "false"),
            ("java_ee_version", "Java EE Version", "Java EE or Jakarta EE version (from imports)", "text", "false"),
            ("framework", "Framework", "ORM/DB framework used (JPA, Hibernate, MyBatis, Spring JDBC, JDBC)", "text", "true"),
            ("access_type", "Access Type", "Table access pattern: R (read), W (write), RW (read/write)", "text", "true"),
        ],
    },
    "python": {
        "data_types": [],
        "table_types": [
            ("TABLE", "Table", "Database table referenced in Python source code", "true"),
            ("VIEW", "View", "Database view referenced in Python source code", "false"),
            ("MODEL", "ORM Model", "ORM model class mapped to a database table", "false"),
        ],
        "storage_formats": [],
        "features": [
            ("source_file", "Source File", "Python source file path where the table is referenced", "text", "false"),
            ("module_path", "Module Path", "Python module path (e.g. myapp.models)", "text", "false"),
            ("class_or_function", "Class / Function", "Class or function name where the table reference was found", "text", "false"),
            ("python_version", "Python Version", "Python version detected from pyproject.toml or setup.py", "text", "false"),
            ("framework", "Framework", "ORM/DB framework used (SQLAlchemy, Django ORM, DB-API)", "text", "true"),
            ("access_type", "Access Type", "Table access pattern: R (read), W (write), RW (read/write)", "text", "true"),
        ],
    },
    "unity_catalog": {
        "data_types": [
            ("BOOLEAN", "boolean", "True/false values"),
            ("BYTE", "numeric", "1-byte signed integer"),
            ("SHORT", "numeric", "2-byte signed integer"),
            ("INT", "numeric", "4-byte signed integer"),
            ("LONG", "numeric", "8-byte signed integer"),
            ("FLOAT", "numeric", "4-byte single precision floating point"),
            ("DOUBLE", "numeric", "8-byte double precision floating point"),
            ("DECIMAL", "numeric", "Arbitrary precision decimal"),
            ("STRING", "string", "Variable-length character string"),
            ("CHAR", "string", "Fixed-length character string"),
            ("VARCHAR", "string", "Variable-length character string with max length"),
            ("DATE", "datetime", "Calendar date (YYYY-MM-DD)"),
            ("TIMESTAMP", "datetime", "Timestamp without timezone"),
            ("TIMESTAMP_NTZ", "datetime", "Timestamp without timezone (NTZ)"),
            ("BINARY", "binary", "Variable-length binary data"),
            ("ARRAY", "complex", "Ordered collection of elements"),
            ("MAP", "complex", "Key-value pairs"),
            ("STRUCT", "complex", "Named fields with typed values"),
        ],
        "table_types": [
            ("MANAGED", "Managed Table", "Unity Catalog manages both data and metadata lifecycle", "true"),
            ("EXTERNAL", "External Table", "Unity Catalog manages metadata only; data stored externally", "false"),
            ("VIEW", "View", "Virtual view defined by a query", "false"),
        ],
        "storage_formats": [
            ("DELTA", "Delta Lake", "Delta Lake format with ACID transactions", "true"),
            ("PARQUET", "Parquet", "Apache Parquet columnar format", "false"),
            ("CSV", "CSV", "Comma-separated values", "false"),
            ("JSON", "JSON", "JSON format", "false"),
            ("AVRO", "Avro", "Apache Avro row-based format", "false"),
            ("ORC", "ORC", "Optimized Row Columnar format", "false"),
        ],
        "features": [
            ("catalog_name", "Catalog Name", "Unity Catalog catalog name", "string", "true"),
            ("schema_name", "Schema Name", "Unity Catalog schema name", "string", "true"),
            ("storage_location", "Storage Location", "External storage location (S3, ADLS, GCS)", "string", "false"),
        ],
    },
}
