"""Pipeline code generator.

Assembles Python code from a DAG of nodes using per-node generators.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone

from app.ml_studio.codegen.nodes.source import SOURCE_GENERATORS
from app.ml_studio.codegen.nodes.transform import TRANSFORM_GENERATORS
from app.ml_studio.codegen.nodes.model import gen_model
from app.ml_studio.codegen.nodes.output import OUTPUT_GENERATORS
from app.ml_studio.codegen.validator import _topo_sort, _find_parent

logger = logging.getLogger(__name__)


def _var(node_id: str) -> str:
    return f"df_{node_id.replace('-', '_').replace(' ', '_')}"


def generate_pipeline_code(
    nodes: list[dict],
    edges: list[dict],
    s3_endpoint: str = "",
    s3_access_key: str = "",
    s3_secret_key: str = "",
) -> str:
    """Generate executable Python code from a pipeline DAG.

    Args:
        nodes: [{id, type, label, config}, ...]
        edges: [{from, to}, ...]
        s3_endpoint: MinIO endpoint URL
        s3_access_key: S3 access key
        s3_secret_key: S3 secret key

    Returns:
        Complete Python script as string.
    """
    node_map = {n["id"]: n for n in nodes}
    order = _topo_sort(nodes, edges)

    has_minio_src = any(node_map[nid]["type"] in ("source_csv", "source_parquet") for nid in order if nid in node_map)
    has_minio_out = any(node_map[nid]["type"] == "output_csv" for nid in order if nid in node_map)
    needs_minio = has_minio_src or has_minio_out
    has_model = any(node_map[nid]["type"].startswith("model_") for nid in order if nid in node_map)

    lines: list[str] = []

    # ── Header ────────────────────────────────────────────
    lines.append('"""')
    lines.append("ML Pipeline — Generated by Argus Insight ML Studio")
    lines.append(f"Generated at: {datetime.now(timezone.utc).isoformat()}")
    lines.append(f"Nodes: {len(nodes)}, Edges: {len(edges)}")
    lines.append('"""')
    lines.append("")
    lines.append("import warnings")
    lines.append('warnings.filterwarnings("ignore")')
    lines.append("")
    lines.append("import numpy as np")
    lines.append("import pandas as pd")
    lines.append("")

    # ── MinIO helpers ─────────────────────────────────────
    if needs_minio:
        lines.append("from io import BytesIO")
        lines.append("from urllib.parse import urlparse")
        lines.append("from minio import Minio")
        lines.append("")
        lines.append("# ── MinIO connection ──────────────────────────────────")
        lines.append(f'S3_ENDPOINT   = "{s3_endpoint}"')
        lines.append(f'S3_ACCESS_KEY = "{s3_access_key}"')
        lines.append(f'S3_SECRET_KEY = "{s3_secret_key}"')
        lines.append("")
        lines.append("_parsed = urlparse(S3_ENDPOINT)")
        lines.append("s3 = Minio(")
        lines.append("    _parsed.netloc,")
        lines.append("    access_key=S3_ACCESS_KEY,")
        lines.append("    secret_key=S3_SECRET_KEY,")
        lines.append('    secure=(_parsed.scheme == "https"),')
        lines.append(")")
        lines.append("")

    if has_minio_src:
        lines.append("")
        lines.append('def _load_csv(bucket: str, key: str, delimiter=None, encoding="utf-8") -> "pd.DataFrame":')
        lines.append('    """Download CSV from MinIO and return as DataFrame."""')
        lines.append("    resp = s3.get_object(bucket, key)")
        lines.append("    buf = BytesIO(resp.read()); resp.close(); resp.release_conn()")
        lines.append("    return pd.read_csv(buf, sep=delimiter, encoding=encoding)")
        lines.append("")
        lines.append('def _load_parquet(bucket: str, key: str) -> "pd.DataFrame":')
        lines.append('    """Download Parquet from MinIO and return as DataFrame."""')
        lines.append("    resp = s3.get_object(bucket, key)")
        lines.append("    buf = BytesIO(resp.read()); resp.close(); resp.release_conn()")
        lines.append("    return pd.read_parquet(buf)")
        lines.append("")

    if has_minio_out:
        lines.append("")
        lines.append('def _minio_upload(bucket: str, key: str, df: "pd.DataFrame") -> None:')
        lines.append('    """Upload DataFrame as CSV to MinIO."""')
        lines.append("    buf = BytesIO()")
        lines.append("    df.to_csv(buf, index=False)")
        lines.append("    buf.seek(0)")
        lines.append('    s3.put_object(bucket, key, buf, length=buf.getbuffer().nbytes, content_type="text/csv")')
        lines.append("")

    # ── Model preparation helper ──────────────────────────
    if has_model:
        lines.append("from sklearn.model_selection import train_test_split")
        lines.append("from sklearn.preprocessing import LabelEncoder")
        lines.append("")
        lines.append("")
        lines.append('def _prepare_for_model(df: "pd.DataFrame", target_col: str) -> tuple:')
        lines.append('    """Separate features/target, encode categoricals, handle NaN."""')
        lines.append("    X = df.drop(columns=[target_col]).copy()")
        lines.append("    y = df[target_col].copy()")
        lines.append("    # Encode categorical features")
        lines.append('    for col in X.select_dtypes(include=["object", "category"]).columns:')
        lines.append("        X[col] = LabelEncoder().fit_transform(X[col].astype(str))")
        lines.append("    # Fill NaN in numeric columns")
        lines.append("    X = X.fillna(X.median(numeric_only=True))")
        lines.append("    # Encode non-numeric target")
        lines.append('    if y.dtype == "object" or y.dtype.name == "category":')
        lines.append("        _le = LabelEncoder()")
        lines.append("        y = pd.Series(_le.fit_transform(y.astype(str)), name=target_col)")
        lines.append('        print(f"  Label mapping: {dict(zip(_le.classes_, _le.transform(_le.classes_)))}")')
        lines.append("    return X, y")
        lines.append("")

    # ── Pipeline body ─────────────────────────────────────
    lines.append("")
    lines.append("# ── Pipeline ─────────────────────────────────────────────")
    lines.append("")

    for nid in order:
        node = node_map.get(nid)
        if not node:
            continue

        ntype = node["type"]
        cfg = node.get("config", {})
        var = _var(nid)
        parent_id = _find_parent(nid, edges)
        parent_var = _var(parent_id) if parent_id else None
        parent_type = node_map[parent_id]["type"] if parent_id and parent_id in node_map else None

        if ntype.startswith("source_"):
            gen = SOURCE_GENERATORS.get(ntype)
            if gen:
                lines.extend(gen(var, cfg))

        elif ntype.startswith("transform_"):
            gen = TRANSFORM_GENERATORS.get(ntype)
            if gen and parent_var:
                lines.extend(gen(var, parent_var, cfg))

        elif ntype.startswith("model_"):
            lines.extend(gen_model(var, ntype, cfg, parent_type, parent_var))

        elif ntype.startswith("output_"):
            gen = OUTPUT_GENERATORS.get(ntype)
            if gen:
                lines.extend(gen(var, cfg))

    lines.append('print("\\n✅ Pipeline execution complete!")')

    return "\n".join(lines)
