apiVersion: v1
kind: ConfigMap
metadata:
  name: argus-airflow-${WORKSPACE_NAME}-custom-config
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
data:
  AIRFLOW__CORE__PARALLELISM: "32"
  AIRFLOW__CORE__MAX_ACTIVE_TASKS_PER_DAG: "16"
  AIRFLOW__CORE__MAX_ACTIVE_RUNS_PER_DAG: "16"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "True"
  AIRFLOW__CORE__DEFAULT_TIMEZONE: "UTC"
  AIRFLOW__CORE__DAG_FILE_PROCESSOR_TIMEOUT: "50"
  AIRFLOW__SCHEDULER__DAG_DIR_LIST_INTERVAL: "30"
  AIRFLOW__SCHEDULER__MIN_FILE_PROCESS_INTERVAL: "30"
  AIRFLOW__SCHEDULER__PARSING_PROCESSES: "2"
  AIRFLOW__SCHEDULER__SCHEDULER_HEARTBEAT_SEC: "5"
  AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT: "120"
  AIRFLOW__WEBSERVER__DEFAULT_UI_TIMEZONE: "UTC"
  AIRFLOW__WEBSERVER__HIDE_PAUSED_DAGS_BY_DEFAULT: "False"
  AIRFLOW__WEBSERVER__PAGE_SIZE: "100"
  AIRFLOW__WEBSERVER__DEFAULT_DAG_RUN_DISPLAY_NUMBER: "25"
  AIRFLOW__WEBSERVER__WORKERS: "4"
  AIRFLOW__LOGGING__LOGGING_LEVEL: "INFO"
  AIRFLOW__LOGGING__FAB_LOGGING_LEVEL: "WARNING"
  AIRFLOW__SMTP__SMTP_HOST: "localhost"
  AIRFLOW__SMTP__SMTP_PORT: "25"
  AIRFLOW__SMTP__SMTP_STARTTLS: "True"
  AIRFLOW__SMTP__SMTP_SSL: "False"
  AIRFLOW__SMTP__SMTP_USER: ""
  AIRFLOW__SMTP__SMTP_PASSWORD: ""
  AIRFLOW__SMTP__SMTP_MAIL_FROM: "airflow@example.com"
