apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-${WORKSPACE_NAME}-dags
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/component: dags
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${AIRFLOW_DAGS_STORAGE_SIZE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-${WORKSPACE_NAME}-logs
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/component: logs
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${AIRFLOW_LOGS_STORAGE_SIZE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-${WORKSPACE_NAME}-db
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${AIRFLOW_DB_STORAGE_SIZE}
