apiVersion: v1
kind: Secret
metadata:
  name: airflow-${WORKSPACE_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: airflow
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
type: Opaque
stringData:
  webserver-secret-key: "${AIRFLOW_SECRET_KEY}"
  fernet-key: "${AIRFLOW_FERNET_KEY}"
  admin-password: "${AIRFLOW_ADMIN_PASSWORD}"
  postgres-password: "${AIRFLOW_DB_PASSWORD}"
  gitlab-token: "${GITLAB_TOKEN}"
