apiVersion: v1
kind: Service
metadata:
  name: argus-redis-${WORKSPACE_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/part-of: argus-insight
spec:
  type: ClusterIP
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
