apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-starrocks-${WORKSPACE_NAME}-fe
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: starrocks
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/component: fe
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${STARROCKS_FE_STORAGE_SIZE}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-starrocks-${WORKSPACE_NAME}-be
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: starrocks
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/component: be
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${STARROCKS_BE_STORAGE_SIZE}
