apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-minio-${WORKSPACE_NAME}-data
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: minio
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: ${MINIO_STORAGE_SIZE}
