apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-unity-catalog-pgdata
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: unity-catalog
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-unity-catalog-data
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: unity-catalog
    app.kubernetes.io/component: server
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
