apiVersion: v1
kind: Secret
metadata:
  name: unity-catalog-secrets
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: unity-catalog
    app.kubernetes.io/part-of: argus-insight
type: Opaque
stringData:
  # Change these values before deploying to production
  postgresql_database: "unity_catalog"
  postgresql_user: "unity_catalog"
  postgresql_password: "Argus!insight2026"
