/**
 * Node documentation for ML Studio Modeler.
 * Each node has descriptions, usage tips, parameter help, and connection info
 * in both English and Korean.
 */

type Lang = "en" | "ko"

interface ParamDoc {
  en: string
  ko: string
}

interface NodeDoc {
  description: { en: string; ko: string }
  whenToUse: { en: string[]; ko: string[] }
  params: Record<string, ParamDoc>
  input: { en: string; ko: string }
  output: { en: string; ko: string }
}

export const NODE_DOCS: Record<string, NodeDoc> = {
  // ── Source ─────────────────────────────────────────────
  source_csv: {
    description: {
      en: "Load a CSV or TSV file from MinIO storage. The first row is used as column headers. Delimiter is auto-detected from file extension.",
      ko: "MinIO 스토리지에서 CSV 또��� TSV 파일을 로드합니다. 첫 번째 행을 컬럼 헤더로 사용하며, 파일 확장자에서 구분자를 자동 감지합니다.",
    },
    whenToUse: {
      en: ["Structured text data for training", "Data exported from Excel or other tools"],
      ko: ["학습에 사용할 구조화된 텍스트 데이터", "Excel 등에서 내보낸 데이터"],
    },
    params: {
      path: { en: "File path in MinIO bucket", ko: "MinIO 버킷 내 파일 경로" },
      bucket: { en: "MinIO bucket name", ko: "MinIO 버킷 이름" },
      delimiter: { en: "Column delimiter (auto, comma, tab, semicolon, pipe)", ko: "컬럼 구분자 (자동, 쉼표, 탭, 세미콜론, 파이프)" },
    },
    input: { en: "None (pipeline start)", ko: "없음 (파이프라인 시작점)" },
    output: { en: "Transform", ko: "Transform" },
  },
  source_parquet: {
    description: {
      en: "Load an Apache Parquet file from MinIO. Columnar format that is efficient for large datasets with many columns.",
      ko: "MinIO에서 Apache Parquet 파일을 로드합니다. 많은 컬럼이 있는 대용량 데이터에 효율적인 컬럼 기반 포맷입니다.",
    },
    whenToUse: {
      en: ["Large datasets (millions of rows)", "Data generated by Spark or Pandas"],
      ko: ["대용량 데이터 (수백만 행)", "Spark 또는 Pandas로 생성한 데이터"],
    },
    params: {
      path: { en: "File path in MinIO bucket", ko: "MinIO 버킷 내 파��� 경로" },
      bucket: { en: "MinIO bucket name", ko: "MinIO 버킷 이름" },
    },
    input: { en: "None (pipeline start)", ko: "없음 (파이프라인 시작점)" },
    output: { en: "Transform", ko: "Transform" },
  },
  source_database: {
    description: {
      en: "Load data from a database using SQL query. Supports PostgreSQL, MariaDB, and Trino deployed in your workspace.",
      ko: "SQL 쿼리로 데이터베이스에서 데이터를 로드합니다. 워크스페이스에 배포된 PostgreSQL, MariaDB, Trino를 지원��니다.",
    },
    whenToUse: {
      en: ["Data stored in relational databases", "Need JOIN or aggregation before training"],
      ko: ["관계형 데이터베이스에 저장된 데이터", "학습 전 JOIN이나 집계가 필요할 때"],
    },
    params: {
      query: { en: "SQL query to execute (e.g., SELECT * FROM customers WHERE active = true)", ko: "실행할 SQL 쿼리 (예: SELECT * FROM customers WHERE active = true)" },
      connection: { en: "Database service in workspace (PostgreSQL, MariaDB, Trino)", ko: "워크스페이스 내 데이터베이스 서비스 (PostgreSQL, MariaDB, Trino)" },
    },
    input: { en: "None (pipeline start)", ko: "없음 (파이프라인 시작점)" },
    output: { en: "Transform", ko: "Transform" },
  },

  // ── Transform ─���───────────────────────────────────────
  transform_drop_cols: {
    description: {
      en: "Remove unwanted columns from the dataset. Columns like ID, name, or phone number that have no predictive value should be dropped before training.",
      ko: "데이터셋에서 불필요한 컬럼을 제거합니다. ID, 이름, 전화번호처럼 예측에 도움이 되지 않는 컬럼은 학습 전에 제거해야 합니다.",
    },
    whenToUse: { en: ["Remove ID or index columns", "Remove personally identifiable information"], ko: ["ID나 인덱스 컬럼 제거", "개인식별정보 제거"] },
    params: { columns: { en: "Comma-separated column names to remove", ko: "제거할 컬럼 이름 (쉼표 구분)" } },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_drop_dup: {
    description: {
      en: "Remove duplicate rows from the dataset. Duplicates can bias training by giving more weight to repeated observations.",
      ko: "데이터셋에서 중복 행을 제거합니다. 중복은 반복된 관측에 더 큰 가중치를 부여하여 학습을 편향시킬 수 있습니다.",
    },
    whenToUse: { en: ["Data may contain repeated records", "After merging multiple data sources"], ko: ["데이터에 반복 레코드가 있을 수 있을 때", "여러 데이터 소스를 병합한 후"] },
    params: {
      subset: { en: "Check duplicates on these columns only (empty = all columns)", ko: "이 컬럼만으로 중복 확인 (비우면 전체 컬럼)" },
      keep: { en: "Which duplicate to keep: first, last, or none (drop all)", ko: "어떤 중복을 유지할지: first, last, none (모두 삭제)" },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_typecast: {
    description: {
      en: "Change column data types. Useful when auto-detection infers the wrong type (e.g., zip code detected as integer should be category).",
      ko: "컬럼 데이터 타입을 변경합니다. 자동 감지가 잘못된 타입을 추론했을 때 유용합니다 (예: 우편번호가 정수로 감지되었지만 카테고리여야 할 때).",
    },
    whenToUse: { en: ["Fix incorrectly detected types", "Convert string numbers to actual numbers"], ko: ["잘못 감지된 타입 수정", "문자열 숫자를 실제 숫자로 변환"] },
    params: { casts: { en: "List of column → target type conversions", ko: "컬럼 → 대상 타입 변환 목록" } },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_outlier: {
    description: {
      en: "Detect and remove statistical outliers. Outliers can significantly distort model training, especially for linear models.",
      ko: "통계적 이상치를 감지하고 제거합니다. 이상치는 특히 선형 모델에서 학습을 크게 왜곡할 수 있습니다.",
    },
    whenToUse: { en: ["Data has extreme values", "Model performance is poor due to outliers"], ko: ["데이터에 극단값이 있을 때", "이상치로 인해 모델 성능이 낮을 때"] },
    params: {
      method: { en: "IQR: uses interquartile range (robust), Z-score: uses standard deviations (assumes normal distribution)", ko: "IQR: 사분위범위 사용 (강건함), Z-score: 표준편차 사용 (정규분포 가정)" },
      threshold: { en: "IQR: multiplier (1.5 = moderate, 3.0 = extreme only). Z-score: number of std devs (3.0 typical)", ko: "IQR: 배수 (1.5 = 보통, 3.0 = 극단만). Z-score: 표준편차 수 (3.0 일반적)" },
      columns: { en: "Apply to specific columns only (empty = all numeric)", ko: "특정 컬럼에만 적용 (비우면 전체 숫자형)" },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_datetime: {
    description: {
      en: "Extract date/time components from a datetime column. Creates new columns like year, month, day, day-of-week that ML models can use as features.",
      ko: "datetime 컬럼에서 날짜/시간 구성 요소를 추출합니다. year, month, day, 요일 등 ML 모델이 피처로 사용할 수 있는 새 컬럼을 생성합니다.",
    },
    whenToUse: { en: ["Data has date or timestamp columns", "Time patterns matter (seasonality, trends)"], ko: ["데이터에 날짜 또는 타임스탬프 컬럼이 있을 때", "시간 패턴이 중요할 때 (계절성, 추세)"] },
    params: {
      column: { en: "Name of the datetime column to extract from", ko: "추출할 datetime 컬럼 이름" },
      extract: { en: "Which components to extract as new columns", ko: "새 컬럼으로 추출할 구성 요소" },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_binning: {
    description: {
      en: "Convert continuous numeric values into discrete bins. Useful for creating age groups, salary brackets, etc.",
      ko: "연속 숫자 값을 이산적인 구간으로 변환합니다. 연령대, 급여 구간 등을 만들 때 유용합니다.",
    },
    whenToUse: { en: ["Create age groups (10s, 20s, 30s)", "Discretize continuous features for tree models"], ko: ["연령대 생성 (10대, 20대, 30대)", "트리 모델을 위한 연속 피처 이산화"] },
    params: {
      column: { en: "Column to bin", ko: "구간을 나눌 컬럼" },
      bins: { en: "Number of bins to create", ko: "생성할 구간 수" },
      strategy: { en: "uniform: equal width, quantile: equal count, kmeans: cluster-based", ko: "uniform: 동일 너비, quantile: 동일 개수, kmeans: 클러스터 기반" },
      labels: { en: "Custom labels for each bin (comma-separated, must match bin count)", ko: "각 구간의 커스텀 라벨 (쉼표 구분, 구간 수와 일치해야 함)" },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_sample: {
    description: {
      en: "Take a random sample of rows. Reduces dataset size for faster experimentation without changing the schema.",
      ko: "랜덤으로 행을 샘플링합니다. 스키마를 변경하지 않고 빠른 실험을 위해 데이터셋 크기를 줄입니다.",
    },
    whenToUse: { en: ["Dataset is too large for quick experiments", "Want faster iteration during development"], ko: ["빠른 실험에 데이터셋이 너무 클 때", "개발 중 빠른 반복을 원할 때"] },
    params: {
      n_rows: { en: "Number of rows to sample", ko: "샘플링할 행 수" },
      random_seed: { en: "Fixed seed for reproducible sampling", ko: "재현 가능한 샘플링을 위한 고정 시드" },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_sort: {
    description: {
      en: "Sort rows by a column. Essential for time-series data to maintain chronological order before splitting.",
      ko: "컬럼 기준으로 행을 정렬합니다. 시계열 데이터에서 분할 전 시간순을 유지하는 데 필수적입니다.",
    },
    whenToUse: { en: ["Time-series data must be in order", "Need consistent row ordering"], ko: ["시계열 데이터가 순서대로 되어야 할 때", "일관된 행 순서가 필요할 때"] },
    params: {
      column: { en: "Column to sort by", ko: "정렬 기준 컬럼" },
      ascending: { en: "True = ascending (A→Z, 1→9), False = descending", ko: "True = 오름차순 (A→Z, 1→9), False = 내림차순" },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_fillnull: {
    description: {
      en: "Handle missing values (NaN/null). Most ML algorithms cannot process missing values, so this step is essential.",
      ko: "결측값(NaN/null)을 처리합니다. 대부분의 ML 알고리즘은 결측값을 처리할 수 없으므로 이 단계는 필수입니다.",
    },
    whenToUse: {
      en: ["Missing column in Column Profile shows > 0", "Before any Model node"],
      ko: ["Column Profile에서 Missing이 0보다 클 때", "모든 Model 노드 전에"],
    },
    params: {
      strategy: {
        en: "mean: average (numeric), median: middle value (robust to outliers), mode: most frequent (categorical), constant: fill with 0, drop: remove rows with missing values",
        ko: "mean: 평균 (수치형), median: 중앙값 (이상치에 강함), mode: 최빈값 (범주형), constant: 0으로 채움, drop: 결측 행 삭제",
      },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_encode: {
    description: {
      en: "Convert categorical (text) columns to numbers. ML models only accept numeric input.",
      ko: "범주형(텍스트) 컬럼을 숫자로 변환합니다. ML 모델은 숫자 입력만 받습니다.",
    },
    whenToUse: {
      en: ["Columns with Type 'string' or 'category'", "After Fill Null, before Scale or Model"],
      ko: ["Type이 'string' 또는 'category'인 컬럼이 있을 때", "Fill Null 이후, Scale 또는 Model ���에"],
    },
    params: {
      method: {
        en: "label: assign 0,1,2... to each category (good for tree models), onehot: create separate binary columns (good for linear models), ordinal: preserve order (low=0, medium=1, high=2)",
        ko: "label: 각 범주에 0,1,2... 부여 (트리 모델에 적합), onehot: 별도 이진 컬럼 생성 (선형 모델에 적합), ordinal: 순서 보존 (low=0, medium=1, high=2)",
      },
    },
    input: { en: "Transform", ko: "Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_scale: {
    description: {
      en: "Normalize numeric features to a common range. Prevents features with large values from dominating the model.",
      ko: "숫자 피처를 공통 범위로 정규화합니다. 값이 큰 피처가 모델을 지배하는 것을 방지합니다.",
    },
    whenToUse: {
      en: ["Required for Linear/Logistic and Neural Network", "Optional for tree models (XGBoost, RF)"],
      ko: ["Linear/Logistic, Neural Network 사용 시 필수", "트리 모델 (XGBoost, RF)에서는 선택적"],
    },
    params: {
      method: {
        en: "standard: mean=0, std=1 (most common), minmax: scale to 0~1 range, robust: uses median/IQR (resistant to outliers)",
        ko: "standard: 평균=0, 표준편차=1 (가장 일반적), minmax: 0~1 범위로 축소, robust: 중앙값/IQR 사용 (이상치에 강함)",
      },
    },
    input: { en: "Transform", ko: "Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },
  transform_split: {
    description: {
      en: "Split data into training and test sets. The model trains on training data and is evaluated on unseen test data. Must be the last Transform before Model.",
      ko: "데이터를 학습용과 테스트용으로 분리합니다. 모델은 학습 데이터로 학습하고 보지 못한 테스트 데이터로 평가됩니다. Model 전 마지막 Transform이어야 합니다.",
    },
    whenToUse: {
      en: ["Always required before any Model node", "Do NOT add Transforms after Split (causes data leakage)"],
      ko: ["모든 Model 노드 전에 반드시 필요", "Split 이후에 Transform을 추가하지 마세요 (데이터 누수 발생)"],
    },
    params: {
      test_size: { en: "Fraction of data for testing (0.2 = 20% test, 80% train). Range: 0.05~0.5", ko: "테스트용 데이터 비율 (0.2 = 20% 테스트, 80% 학습). ���위: 0.05~0.5" },
      stratify: { en: "Maintain class ratio in train/test (important for imbalanced classification)", ko: "학습/테스트에서 클래스 비율 유지 (불균형 분류에서 중요)" },
    },
    input: { en: "Transform", ko: "Transform" },
    output: { en: "Model only", ko: "Model만 연결 가능" },
  },
  transform_filter: {
    description: {
      en: "Remove rows based on a condition expression. Use Python/Pandas syntax.",
      ko: "조건식에 따라 행을 제거합니다. Python/Pandas 구문을 사용합니다.",
    },
    whenToUse: {
      en: ["Remove outliers (e.g., age > 120)", "Select specific subset of data"],
      ko: ["이상치 제거 (예: age > 120)", "특정 데이터 부분 집합 선택"],
    },
    params: {
      condition: { en: "Python expression: age > 18, status == 'active', salary.between(30000, 200000)", ko: "Python 표현식: age > 18, status == 'active', salary.between(30000, 200000)" },
    },
    input: { en: "Source or Transform", ko: "Source 또는 Transform" },
    output: { en: "Transform", ko: "Transform" },
  },
  transform_feature: {
    description: {
      en: "Create new features from existing columns. Domain-specific features often dramatically improve model performance.",
      ko: "기존 컬럼을 조합하여 새 피처를 생성합니다. 도메인 지식을 반영한 피처는 모델 성능을 크게 향상시킵니다.",
    },
    whenToUse: {
      en: ["Create meaningful derived variables (e.g., BMI = weight/height²)", "Combine columns (e.g., total = price × quantity)"],
      ko: ["의미 있는 파생 변수 생성 (예: BMI = 체중/키²)", "컬럼 조합 (예: 총액 = 단가 × 수량)"],
    },
    params: {
      expression: { en: "Python expression: price * quantity, np.log(salary + 1), age // 10 * 10", ko: "Python 표현식: price * quantity, np.log(salary + 1), age // 10 * 10" },
    },
    input: { en: "Transform", ko: "Transform" },
    output: { en: "Transform or Model", ko: "Transform 또는 Model" },
  },

  // ── Model ───────��─────────────────────────────���───────
  model_xgboost: {
    description: {
      en: "Gradient Boosted Decision Tree ensemble. Achieves top accuracy on structured tabular data. Handles missing values natively.",
      ko: "Gradient Boosted Decision Tree 앙상블. 구조화된 테이블 데이터에서 최고 정확도를 달성합니다. 결측값을 자체 처리합니다.",
    },
    whenToUse: {
      en: ["Accuracy is top priority", "Medium to large tabular data", "Kaggle competition default choice"],
      ko: ["정확도가 최우선일 때", "중~대규모 테이블 데이터", "Kaggle 경진대회 기본 선택"],
    },
    params: {
      n_estimators: { en: "Number of boosting rounds. Higher = more accurate but slower. Range: 50~1000", ko: "부스팅 라운드 수. 높을수록 정확하지만 느림. 범위: 50~1000" },
      max_depth: { en: "Maximum tree depth. Higher = more complex, risk of overfitting. Range: 3~15", ko: "최대 트리 깊이. 높을수록 복잡하고 과적합 위험. 범위: 3~15" },
      learning_rate: { en: "Step size shrinkage. Lower = more robust but needs more estimators. Range: 0.01~0.3", ko: "학습률. 낮을수록 안정적이지만 더 많은 라운드 필요. 범위: 0.01~0.3" },
    },
    input: { en: "Transform (Split)", ko: "Transform (Split)" },
    output: { en: "Output", ko: "Output" },
  },
  model_lightgbm: {
    description: {
      en: "Microsoft's Light Gradient Boosting. Faster and more memory-efficient than XGBoost, especially for large datasets.",
      ko: "Microsoft의 경량 Gradient Boosting. XGBoost보다 빠르고 메모리 효율적이며, 특히 대용량 데이터에 유리합니다.",
    },
    whenToUse: {
      en: ["Large datasets (1M+ rows)", "Fast training needed", "Memory-constrained environment"],
      ko: ["대용량 데이터 (100만 행 이상)", "빠른 학습이 필요할 때", "메모리 제한 환경"],
    },
    params: {
      n_estimators: { en: "Number of boosting rounds. Range: 50~1000", ko: "부스팅 라운드 수. 범위: 50~1000" },
      max_depth: { en: "Maximum tree depth. -1 = no limit. Range: -1 or 3~15", ko: "최대 트리 깊이. -1 = 제한 없음. 범위: -1 또는 3~15" },
      learning_rate: { en: "Step size shrinkage. Range: 0.01~0.3", ko: "학습률. 범위: 0.01~0.3" },
    },
    input: { en: "Transform (Split)", ko: "Transform (Split)" },
    output: { en: "Output", ko: "Output" },
  },
  model_rf: {
    description: {
      en: "Ensemble of independent decision trees. Robust, less prone to overfitting, and provides good baseline performance.",
      ko: "독립적인 결정 트리 앙상블. 과적합에 강하고 안정적인 기본 성능을 제공��니다.",
    },
    whenToUse: {
      en: ["Good first model to try", "When overfitting is a concern", "Need interpretable feature importance"],
      ko: ["첫 번째 시도 모델로 적합", "과적합이 걱정될 때", "해석 가능한 피처 중요도가 필요할 때"],
    },
    params: {
      n_estimators: { en: "Number of trees. More = more stable. Range: 50~500", ko: "트리 개수. 많을수록 안정적. 범위: 50~500" },
      max_depth: { en: "Maximum tree depth. null = unlimited. Range: null or 3~30", ko: "최대 트리 깊이. null = 무제한. 범위: null ��는 3~30" },
    },
    input: { en: "Transform (Split)", ko: "Transform (Split)" },
    output: { en: "Output", ko: "Output" },
  },
  model_linear: {
    description: {
      en: "Simple linear model. Fast, fully interpretable. Uses Linear Regression for numeric targets, Logistic Regression for classification.",
      ko: "단순 선형 모델. 빠르고 완전히 해석 가능합니다. 수치 예측은 Linear Regression, 분류는 Logistic Regression을 사용합니다.",
    },
    whenToUse: {
      en: ["Data has linear relationships", "Interpretability is top priority", "Use as baseline to compare with complex models"],
      ko: ["데이터에 선형 관계가 있을 때", "해석 가능성이 최우선일 때", "복잡한 모델과 비교할 기준선으로"],
    },
    params: {
      max_iter: { en: "Maximum iterations for convergence. Increase if model doesn't converge. Range: 100~2000", ko: "수렴을 위한 최대 반복 횟수. 수렴하지 않으면 증가. 범위: 100~2000" },
    },
    input: { en: "Transform (Split)", ko: "Transform (Split)" },
    output: { en: "Output", ko: "Output" },
  },
  model_automl: {
    description: {
      en: "Automatically tries multiple algorithms and hyperparameters within a time limit. Selects the best performing model.",
      ko: "시간 제한 내에서 여러 알고리즘과 하이퍼파라미터를 자동으로 시도합니다. 가장 성능이 좋은 모델을 선택합니다.",
    },
    whenToUse: {
      en: ["Don't know which model is best", "Have time but limited ML expertise", "Want to explore many options automatically"],
      ko: ["어떤 모델이 좋을지 모를 때", "시간은 있지만 ML 전문 지식이 부족할 때", "많은 옵션을 자동으로 탐색하고 싶을 때"],
    },
    params: {
      time_limit: { en: "Maximum training time in seconds. 300 = 5 min, 600 = 10 min", ko: "최대 학습 시간(초). 300 = 5분, 600 = 10분" },
      metric: { en: "Optimization metric. auto = best for task type. f1/accuracy for classification, rmse for regression", ko: "최적화 메트릭. auto = 태스크에 맞게 자동 선택. 분류: f1/accuracy, 회귀: rmse" },
    },
    input: { en: "Transform (Split)", ko: "Transform (Split)" },
    output: { en: "Output", ko: "Output" },
  },

  // ── Output ────────────────────────────────────────────
  output_mlflow: {
    description: {
      en: "Log trained model, metrics, and parameters to MLflow. Enables experiment tracking, model versioning, and later deployment.",
      ko: "학습된 모델, 메트릭, 파라미터를 MLflow에 기록합니다. 실험 추적, 모델 버전 관리, 이후 배포가 가능합니다.",
    },
    whenToUse: {
      en: ["Save experiment results for comparison", "Want to deploy the model later via KServe"],
      ko: ["실험 결과를 저장하고 비교할 때", "나중에 KServe로 모델을 배포하려 할 때"],
    },
    params: {
      experiment_name: { en: "MLflow experiment name. Multiple runs under the same name are compared together", ko: "MLflow 실험 이름. 같은 이름의 여러 실행을 함께 비교합니다" },
    },
    input: { en: "Model", ko: "Model" },
    output: { en: "None (pipeline end)", ko: "없음 (파이프라인 끝)" },
  },
  output_evaluate: {
    description: {
      en: "Calculate model performance metrics and feature importance. Classification: F1, Accuracy, AUC. Regression: RMSE, MAE, R².",
      ko: "모델 성능 메트릭과 피처 중요도를 계산합니다. 분류: F1, Accuracy, AUC. 회귀: RMSE, MAE, R².",
    },
    whenToUse: {
      en: ["Always recommended to evaluate model quality", "Compare multiple models' performance"],
      ko: ["모델 품질 평가에 항상 권장", "여러 모델의 성능 비교"],
    },
    params: {
      metrics: { en: "List of metrics to calculate (f1, accuracy, auc, rmse, mae, r2)", ko: "계산할 메트릭 목록 (f1, accuracy, auc, rmse, mae, r2)" },
    },
    input: { en: "Model", ko: "Model" },
    output: { en: "None (pipeline end)", ko: "없음 (파이프라인 끝)" },
  },
  output_kserve: {
    description: {
      en: "Deploy the trained model as a REST API via KServe. External systems can send prediction requests to the endpoint.",
      ko: "학습된 모델을 KServe를 통해 REST API로 배포합니다. 외부 시스템에서 예측 요청을 보낼 수 있습니다.",
    },
    whenToUse: {
      en: ["Deploy model to production", "Need real-time predictions via API"],
      ko: ["모델을 프로덕션에 배포할 때", "API를 통한 실시간 예측이 필요할 때"],
    },
    params: {
      cpu: { en: "CPU allocation for serving (e.g., '1' = 1 core)", ko: "서빙용 CPU 할당 (예: '1' = 1코어)" },
      memory: { en: "Memory allocation for serving (e.g., '2Gi')", ko: "서빙용 메모리 할당 (예: '2Gi')" },
    },
    input: { en: "Model", ko: "Model" },
    output: { en: "None (pipeline end)", ko: "없음 (파이프라인 끝)" },
  },
  output_csv: {
    description: {
      en: "Export predictions or processed data to a CSV file in MinIO. Useful for sharing results with other systems.",
      ko: "예측 결과나 처리된 데이터를 MinIO에 CSV 파일로 내보냅니다. 다른 시스템과 결과를 공유할 때 유용합니다.",
    },
    whenToUse: {
      en: ["Share processed data with other tools", "Save prediction results as file"],
      ko: ["처리된 데이터를 다른 도구와 공유할 때", "예측 결과를 파일로 저장할 때"],
    },
    params: {
      bucket: { en: "MinIO bucket to save the file", ko: "파일을 저장할 MinIO 버킷" },
      path: { en: "Directory path in the bucket", ko: "버킷 내 디렉토리 경로" },
      filename: { en: "Output file name (.csv)", ko: "출력 파일명 (.csv)" },
    },
    input: { en: "Model", ko: "Model" },
    output: { en: "None (pipeline end)", ko: "없음 (파이프라인 끝)" },
  },
}

export type { Lang, NodeDoc, ParamDoc }
