apiVersion: v1
kind: ConfigMap
metadata:
  name: argus-postgresql-${WORKSPACE_NAME}-custom-config
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
data:
  custom.conf: |
    max_connections = 100
    shared_buffers = 128MB
    work_mem = 4MB
    maintenance_work_mem = 64MB
    effective_cache_size = 512MB
    wal_buffers = 4MB
    checkpoint_completion_target = 0.9
    random_page_cost = 4.0
    log_min_duration_statement = -1
    log_statement = none
