apiVersion: v1
kind: Service
metadata:
  name: argus-postgresql-${WORKSPACE_NAME}
  namespace: ${K8S_NAMESPACE}
  labels:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
    app.kubernetes.io/part-of: argus-insight
    argus-insight/workspace: ${WORKSPACE_NAME}
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
  selector:
    app.kubernetes.io/name: postgresql
    app.kubernetes.io/instance: ${WORKSPACE_NAME}
