server.env=dev

## Identity Provider authorization parameters
server.authorization=enable
server.authorization-url=
server.token-url=
server.client-id=
server.client-secret=
server.redirect-port=
# D-Days H-Hours M-Minutes S-Seconds
server.cookie-timeout=P5D

## Experimental Feature Flags
server.managed-table.enabled=false
