apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-config
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: config
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-logs
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: logs
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitlab-data
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: gitlab
    app.kubernetes.io/component: data
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
