"""Tests for hostmgr service - hostname, /etc/hosts, /etc/resolv.conf."""

import zipfile
from unittest.mock import AsyncMock, patch

import pytest

from app.hostmgr import service

# ---------------------------------------------------------------------------
# Fixtures
# ---------------------------------------------------------------------------


@pytest.fixture
def hosts_file(tmp_path):
    """Create a temporary /etc/hosts file."""
    f = tmp_path / "hosts"
    f.write_text(
        "127.0.0.1   localhost\n::1         localhost\n192.168.1.10 myserver myserver.example.com\n"
    )
    return f


@pytest.fixture
def resolv_file(tmp_path):
    """Create a temporary /etc/resolv.conf file."""
    f = tmp_path / "resolv.conf"
    f.write_text(
        "# Generated by NetworkManager\n"
        "search example.com\n"
        "nameserver 8.8.8.8\n"
        "nameserver 8.8.4.4\n"
        "options edns0 trust-ad\n"
    )
    return f


# ---------------------------------------------------------------------------
# Hostname tests
# ---------------------------------------------------------------------------


async def test_get_hostname():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.side_effect = [
            (0, "myhost", ""),
            (0, "myhost.example.com", ""),
        ]
        result = await service.get_hostname()

    assert result.hostname == "myhost"
    assert result.fqdn == "myhost.example.com"


async def test_get_hostname_fqdn_empty_falls_back():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.side_effect = [
            (0, "myhost", ""),
            (0, "", "hostname: Name or service not known"),
        ]
        result = await service.get_hostname()

    assert result.hostname == "myhost"
    assert result.fqdn == "myhost"


async def test_change_hostname_success():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.return_value = (0, "", "")
        result = await service.change_hostname("newhost")

    assert result.success is True
    assert "newhost" in result.message


async def test_change_hostname_failure():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.return_value = (1, "", "Could not set hostname")
        result = await service.change_hostname("bad-host")

    assert result.success is False
    assert "Failed" in result.message


async def test_validate_hostname_consistent():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.side_effect = [
            (0, "myhost", ""),
            (0, "myhost.example.com", ""),
        ]
        result = await service.validate_hostname()

    assert result.is_consistent is True
    assert result.hostname == "myhost"
    assert result.fqdn == "myhost.example.com"


async def test_validate_hostname_inconsistent():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.side_effect = [
            (0, "myhost", ""),
            (0, "otherhost.example.com", ""),
        ]
        result = await service.validate_hostname()

    assert result.is_consistent is False
    assert "mismatch" in result.message.lower()


# ---------------------------------------------------------------------------
# /etc/hosts tests
# ---------------------------------------------------------------------------


def test_read_hosts_file(hosts_file):
    with patch.object(service, "HOSTS_FILE", hosts_file):
        result = service.read_hosts_file()

    assert "127.0.0.1" in result.content
    assert "myserver" in result.content


def test_read_hosts_file_not_found(tmp_path):
    missing = tmp_path / "nonexistent"
    with patch.object(service, "HOSTS_FILE", missing):
        with pytest.raises(FileNotFoundError):
            service.read_hosts_file()


def test_update_hosts_file(tmp_path):
    target = tmp_path / "hosts"
    target.write_text("old content")
    new_content = "127.0.0.1 localhost\n"

    with patch.object(service, "HOSTS_FILE", target):
        result = service.update_hosts_file(new_content)

    assert result.success is True
    assert target.read_text() == new_content


def test_backup_hosts_file(hosts_file, tmp_path):
    backup_dir = tmp_path / "backups"
    with (
        patch.object(service, "HOSTS_FILE", hosts_file),
        patch("app.core.config.settings") as mock_settings,
    ):
        mock_settings.backup_dir = backup_dir
        result = service.backup_hosts_file()

    assert result.success is True
    assert zipfile.is_zipfile(result.backup_path)

    with zipfile.ZipFile(result.backup_path) as zf:
        assert "hosts" in zf.namelist()


def test_backup_hosts_file_missing(tmp_path):
    missing = tmp_path / "nonexistent"
    backup_dir = tmp_path / "backups"
    with (
        patch.object(service, "HOSTS_FILE", missing),
        patch("app.core.config.settings") as mock_settings,
    ):
        mock_settings.backup_dir = backup_dir
        result = service.backup_hosts_file()

    assert result.success is False


# ---------------------------------------------------------------------------
# /etc/resolv.conf tests
# ---------------------------------------------------------------------------


def test_read_resolv_conf(resolv_file):
    with patch.object(service, "RESOLV_CONF", resolv_file):
        result = service.read_resolv_conf()

    assert "nameserver" in result.content
    assert "8.8.8.8" in result.content


def test_read_resolv_conf_not_found(tmp_path):
    missing = tmp_path / "nonexistent"
    with patch.object(service, "RESOLV_CONF", missing):
        with pytest.raises(FileNotFoundError):
            service.read_resolv_conf()


def test_update_resolv_conf(tmp_path):
    target = tmp_path / "resolv.conf"
    target.write_text("old")
    new_content = "nameserver 1.1.1.1\n"

    with patch.object(service, "RESOLV_CONF", target):
        result = service.update_resolv_conf(new_content)

    assert result.success is True
    assert target.read_text() == new_content


def test_backup_resolv_conf(resolv_file, tmp_path):
    backup_dir = tmp_path / "backups"
    with (
        patch.object(service, "RESOLV_CONF", resolv_file),
        patch("app.core.config.settings") as mock_settings,
    ):
        mock_settings.backup_dir = backup_dir
        result = service.backup_resolv_conf()

    assert result.success is True
    assert zipfile.is_zipfile(result.backup_path)


# ---------------------------------------------------------------------------
# Nameserver tests
# ---------------------------------------------------------------------------


def test_get_nameservers(resolv_file):
    with patch.object(service, "RESOLV_CONF", resolv_file):
        result = service.get_nameservers()

    assert len(result.nameservers) == 2
    assert result.nameservers[0].address == "8.8.8.8"
    assert result.nameservers[1].address == "8.8.4.4"
    assert "example.com" in result.search_domains
    assert "edns0" in result.options


def test_get_nameservers_missing_file(tmp_path):
    missing = tmp_path / "nonexistent"
    with patch.object(service, "RESOLV_CONF", missing):
        result = service.get_nameservers()

    assert result.nameservers == []
    assert result.raw == ""


def test_update_nameservers(resolv_file):
    with patch.object(service, "RESOLV_CONF", resolv_file):
        result = service.update_nameservers(["1.1.1.1", "1.0.0.1"])

    assert result.success is True
    content = resolv_file.read_text()
    assert "nameserver 1.1.1.1" in content
    assert "nameserver 1.0.0.1" in content
    # Old nameservers should be gone
    assert "nameserver 8.8.8.8" not in content
    # search/options should be preserved
    assert "search example.com" in content
    assert "options edns0 trust-ad" in content


def test_update_nameservers_empty_list(resolv_file):
    with patch.object(service, "RESOLV_CONF", resolv_file):
        result = service.update_nameservers([])

    assert result.success is False
    assert "required" in result.message.lower()


def test_update_nameservers_creates_file(tmp_path):
    missing = tmp_path / "resolv.conf"
    with patch.object(service, "RESOLV_CONF", missing):
        result = service.update_nameservers(["1.1.1.1"])

    assert result.success is True
    assert "nameserver 1.1.1.1" in missing.read_text()


# ---------------------------------------------------------------------------
# Ulimit tests
# ---------------------------------------------------------------------------


@pytest.fixture
def limits_file(tmp_path):
    """Create a temporary /etc/security/limits.conf file."""
    f = tmp_path / "limits.conf"
    f.write_text(
        "# /etc/security/limits.conf\n"
        "#\n"
        "# <domain> <type> <item> <value>\n"
        "#\n"
        "*\tsoft\tnofile\t1024\n"
        "*\thard\tnofile\t4096\n"
        "alice\tsoft\tnofile\t2048\n"
        "alice\thard\tnofile\t8192\n"
    )
    return f


async def test_get_ulimit_all():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.side_effect = [
            (0, "1024", ""),  # -n soft
            (0, "4096", ""),  # -n hard
            (0, "63328", ""),  # -u soft
            (0, "63328", ""),  # -u hard
            (0, "unlimited", ""),  # -v soft
            (0, "unlimited", ""),  # -v hard
            (0, "8192", ""),  # -s soft
            (0, "unlimited", ""),  # -s hard
            (0, "0", ""),  # -c soft
            (0, "unlimited", ""),  # -c hard
        ]
        result = await service.get_ulimit_all()

    assert len(result.entries) == 5
    nofile = result.entries[0]
    assert nofile.option == "-n"
    assert nofile.resource == "open files"
    assert nofile.soft == "1024"
    assert nofile.hard == "4096"


async def test_get_ulimit_specific():
    with patch.object(service, "_run", new_callable=AsyncMock) as mock_run:
        mock_run.side_effect = [
            (0, "1024", ""),
            (0, "4096", ""),
        ]
        result = await service.get_ulimit("-n")

    assert result.option == "-n"
    assert result.resource == "open files"
    assert result.soft == "1024"
    assert result.hard == "4096"


async def test_get_ulimit_invalid_option():
    with pytest.raises(ValueError, match="Unsupported"):
        await service.get_ulimit("-x")


async def test_set_ulimit(limits_file):
    with (
        patch.object(service, "LIMITS_CONF", limits_file),
    ):
        result = await service.set_ulimit("-n", "65536")

    assert result.success is True
    content = limits_file.read_text()
    assert "*\tsoft\tnofile\t65536" in content
    assert "*\thard\tnofile\t65536" in content


async def test_set_ulimit_invalid_option():
    result = await service.set_ulimit("-x", "100")
    assert result.success is False
    assert "Unsupported" in result.message


def test_set_user_max_open_files_new_user(limits_file):
    from app.hostmgr.schemas import LimitsConfSetRequest

    request = LimitsConfSetRequest(user="bob", soft="4096", hard="8192")
    with patch.object(service, "LIMITS_CONF", limits_file):
        result = service.set_user_max_open_files(request)

    assert result.success is True
    content = limits_file.read_text()
    assert "bob\tsoft\tnofile\t4096" in content
    assert "bob\thard\tnofile\t8192" in content
    # Existing entries should be preserved
    assert "alice\tsoft\tnofile\t2048" in content


def test_set_user_max_open_files_update_existing(limits_file):
    from app.hostmgr.schemas import LimitsConfSetRequest

    request = LimitsConfSetRequest(user="alice", soft="10000", hard="20000")
    with patch.object(service, "LIMITS_CONF", limits_file):
        result = service.set_user_max_open_files(request)

    assert result.success is True
    content = limits_file.read_text()
    assert "alice\tsoft\tnofile\t10000" in content
    assert "alice\thard\tnofile\t20000" in content
    # Old values should be gone
    assert "alice\tsoft\tnofile\t2048" not in content
    assert "alice\thard\tnofile\t8192" not in content


def test_set_user_max_open_files_all_users(limits_file):
    from app.hostmgr.schemas import LimitsConfSetRequest

    request = LimitsConfSetRequest(user="*", soft="65536", hard="65536")
    with patch.object(service, "LIMITS_CONF", limits_file):
        result = service.set_user_max_open_files(request)

    assert result.success is True
    content = limits_file.read_text()
    assert "*\tsoft\tnofile\t65536" in content
    assert "*\thard\tnofile\t65536" in content
    # Old * entries should be gone
    assert "*\tsoft\tnofile\t1024" not in content


def test_set_user_max_open_files_missing_file(tmp_path):
    from app.hostmgr.schemas import LimitsConfSetRequest

    missing = tmp_path / "nonexistent"
    request = LimitsConfSetRequest(user="bob", soft="1024", hard="2048")
    with patch.object(service, "LIMITS_CONF", missing):
        result = service.set_user_max_open_files(request)

    assert result.success is False
    assert "not found" in result.message.lower()


def test_parse_limits_conf(limits_file):
    content = limits_file.read_text()
    entries = service._parse_limits_conf(content)
    assert len(entries) == 4
    assert entries[0].domain == "*"
    assert entries[0].type == "soft"
    assert entries[0].item == "nofile"
    assert entries[0].value == "1024"


def test_update_limits_conf_preserves_comments(limits_file):
    with patch.object(service, "LIMITS_CONF", limits_file):
        service._update_limits_conf("bob", "nofile", "1000", "2000")

    content = limits_file.read_text()
    assert "# /etc/security/limits.conf" in content
    assert "bob\tsoft\tnofile\t1000" in content
