apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-prometheus
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-alertmanager
  namespace: argus-insight
  labels:
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
