apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: argus-prometheus
  namespace: argus-insight
  labels:
    app.kubernetes.io/part-of: argus-insight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
